#DIAGRAM SCENE ZDEPTHS
ZVALUE_SURFACE_MESH = 1000

ZVALUE_POINT = 120
ZVALUE_LINE = 110

ZVALUE_POINT_MOVE = 60
ZVALUE_LINE_MOVE = 50

ZVALUE_POINT_TMP = 11
ZVALUE_LINE_TMP = 10

ZVALUE_POLYGON = 0

ZVALUE_SHAPEFILES = -10

# TODO: What are those for? Check usage and existence necessity for these structures
ZVALUE_DIAGRAM_VIEW = -9
ZVALUE_BLINK = -1000

ZVALUE_CANVAS = -1000
