# requires tags, refs and autoconversion to work properly

problem: !SequentialCoupling
  description: Simple dual porosity test - steady flow, simple transport
  mesh:
    mesh_file: input/dual_por.msh
  primary_equation: !Steady_MH
    balance: true
    input_fields:
      - conductivity: 1.0e-15
        r_set: ALL
      - bc_pressure: 0
        bc_type: dirichlet
        r_set: BOUNDARY
    output:
      output_fields: [pressure_p0, pressure_p1, velocity_p0]
      output_stream: !ref /output_streams/0
    solver: !Petsc
      a_tol: 1.0e-07
  secondary_equation: !TransportOperatorSplitting
    balance:
      cumulative: true
    input_fields:
      - init_conc: [1.0, 0.0]
        porosity: 0.25
        r_set: ALL
      - bc_conc: 0
        r_set: BOUNDARY
    output_stream: !ref /output_streams/1
    reaction_term: !DualPorosity
      input_fields:
        - diffusion_rate_immobile: [0.01, 0.01]
          init_conc_immobile: [0.0, 0.0]
          porosity_immobile: 0.25
          r_set: ALL
      reaction_immobile: ../reaction_mobile
      reaction_mobile: !FirstOrderReaction
        reactions:
          - products: B
            reactants: A
            reaction_rate: 0.277258872
      scheme_tolerance: 0.0
    substances: [A, B]
    time:
      end_time: 5.0

output_streams:
  - file: dual_por.pvd
    format: !vtk
      variant: ascii
    name: flow_output_stream
  - file: dual_por_transport.pvd
    format: !vtk
      variant: ascii
    name: transport_output_stream
    time_step: 0.5