# Test config file
# Editing may break tests

output_streams:
  - file:
    format: flow_output_stream
  - file: dual_por_transport.pvd
    time_step: 0.5

problem:
  description: Some, text
  primary_equation:
    balance: true
    input_fields:
      - {conductivity: 1.0e-15, r_set: ALL}
      - {bc_pressure: 0, bc_type: dirichlet, r_set: BOUNDARY}