# Minimal invalid example for flow_1.8.2._input_format.json
# This is not an acutal config file -- only for testing purposes
# Does not contain references
# Does not require autocomplete
# Editing may break tests

problem: !SequentialCoupling
  mesh: {mesh_file: input/dual_por.msh}
  unknown: test  # unknown key - validation warning
  primary_equation: !Steady_MH  # validation error - missing key
    balance: true
    input_fields: !uselss_tag
        - &in1
          bc_pressure: 0
          bc_type: dirichlet
          r_set: BOUNDARY
        - *in1
        - *in2
        - *in3
    output:
      output_fields: []
      output_stream:
        file: dual_por.pvd
        -  # parsing error, info - modification ignored
        time_step: 3