FROM flow123d/v2.1.0:user

RUN apt-get update && apt-get install -y \
  python3-pip \
  python3-paramiko

RUN pip3 install Markdown==2.6.2
RUN pip3 install PyYAML==3.11
RUN pip3 install six==1.10.0
RUN pip3 install numpy==1.12.0
RUN pip3 install scipy==0.18.1
RUN pip3 install psutil
