hydra:
  cli_params: []
  flow_path: /share/apps/flow123d/flow123d-2.0.0_rc/bin/flow123d
  module_add: null
  name: hydra
  pbs_params: []
  python_exec: /opt/python/bin/python3.3
  scl_enable_exec: null
local:
  cli_params: []
  flow_path: /opt/flow/Flow123d-2.0.0_rc-Linux/bin/flow123d
  module_add: null
  name: local
  pbs_params: []
  python_exec: python3
  scl_enable_exec: null
