name: Build Win

on:
  push:
    branches:
      - release*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize submodules
      run: |
        cp .gitmodules_https .gitmodules
        git submodule init
        git submodule update
        git submodule sync
        git checkout .gitmodules

    - name: Download prerequisites
      run: |
        wget -r -np -nd -nv -R "index.html*" -e robots=off -P build/win_x86 https://geomop.nti.tul.cz/prerequisites/
        cd build/win_x86
        unzip gmsh-3.0.5-Windows64.zip
        mv gmsh-3.0.5-Windows gmsh

    - name: Create Windows installer
      run: |
        mkdir -p dist
        docker run -i -u $(id -u):$(id -u) -v $(pwd):/nsis-project flow123d/nsis-3.05-1 /nsis-project/win_x86.nsi

    - uses: actions/upload-artifact@v1
      with:
        name: win_install
        path: dist
