name: Build Lin

on:
  push:
    branches:
      - release*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize submodules
      run: |
        cp .gitmodules_https .gitmodules
        git submodule init
        git submodule update
        git submodule sync
        git checkout .gitmodules

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts

    - name: Create debian package
      run: |
        mkdir -p dist
        export VERSION=$(head -n 1 VERSION)
        cd build
        make debian

    - uses: actions/upload-artifact@v1
      with:
        name: lin_install
        path: dist
