# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InitDialog(object):
    def setupUi(self, InitDialog):
        InitDialog.setObjectName("InitDialog")
        InitDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        InitDialog.resize(687, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InitDialog.sizePolicy().hasHeightForWidth())
        InitDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/geomop-color-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InitDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(InitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_recent_button = QtWidgets.QPushButton(InitDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/folder_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_recent_button.setIcon(icon1)
        self.open_recent_button.setObjectName("open_recent_button")
        self.verticalLayout.addWidget(self.open_recent_button)
        self.open_existing_button = QtWidgets.QPushButton(InitDialog)
        self.open_existing_button.setIcon(icon1)
        self.open_existing_button.setObjectName("open_existing_button")
        self.verticalLayout.addWidget(self.open_existing_button)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.from_shape_button = QtWidgets.QPushButton(InitDialog)
        self.from_shape_button.setIcon(icon1)
        self.from_shape_button.setObjectName("from_shape_button")
        self.verticalLayout.addWidget(self.from_shape_button)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.min_x_lineedit = QtWidgets.QLineEdit(InitDialog)
        self.min_x_lineedit.setPlaceholderText("")
        self.min_x_lineedit.setObjectName("min_x_lineedit")
        self.gridLayout.addWidget(self.min_x_lineedit, 1, 2, 1, 1)
        self.size_y_lineedit = QtWidgets.QLineEdit(InitDialog)
        self.size_y_lineedit.setObjectName("size_y_lineedit")
        self.gridLayout.addWidget(self.size_y_lineedit, 3, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(InitDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(InitDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.min_y_lineedit = QtWidgets.QLineEdit(InitDialog)
        self.min_y_lineedit.setObjectName("min_y_lineedit")
        self.gridLayout.addWidget(self.min_y_lineedit, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(InitDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(InitDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.size_x_lineedit = QtWidgets.QLineEdit(InitDialog)
        self.size_x_lineedit.setObjectName("size_x_lineedit")
        self.gridLayout.addWidget(self.size_x_lineedit, 1, 6, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.from_coords_button = QtWidgets.QPushButton(InitDialog)
        self.from_coords_button.setObjectName("from_coords_button")
        self.gridLayout_4.addWidget(self.from_coords_button, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(InitDialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionOpen_existing = QtWidgets.QAction(InitDialog)
        self.actionOpen_existing.setCheckable(True)
        self.actionOpen_existing.setObjectName("actionOpen_existing")
        self.label_5.setBuddy(self.min_y_lineedit)
        self.label_3.setBuddy(self.min_x_lineedit)
        self.label_4.setBuddy(self.size_x_lineedit)
        self.label_6.setBuddy(self.size_y_lineedit)

        self.retranslateUi(InitDialog)
        self.open_existing_button.clicked.connect(InitDialog.accept)
        self.open_recent_button.clicked.connect(InitDialog.accept)
        self.from_shape_button.clicked.connect(InitDialog.accept)
        self.from_coords_button.clicked.connect(InitDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(InitDialog)
        InitDialog.setTabOrder(self.min_x_lineedit, self.min_y_lineedit)
        InitDialog.setTabOrder(self.min_y_lineedit, self.size_x_lineedit)
        InitDialog.setTabOrder(self.size_x_lineedit, self.size_y_lineedit)

    def retranslateUi(self, InitDialog):
        _translate = QtCore.QCoreApplication.translate
        InitDialog.setWindowTitle(_translate("InitDialog", "Initialize work area from:"))
        self.open_recent_button.setText(_translate("InitDialog", "Open recent           "))
        self.open_existing_button.setText(_translate("InitDialog", "Open existing        "))
        self.from_shape_button.setText(_translate("InitDialog", "Init from shape file"))
        self.label_5.setText(_translate("InitDialog", "min y:"))
        self.label_3.setText(_translate("InitDialog", "min x:"))
        self.label_4.setText(_translate("InitDialog", "&x size:"))
        self.label_6.setText(_translate("InitDialog", "&y size:"))
        self.from_coords_button.setText(_translate("InitDialog", "Init as rectangle"))
        self.pushButton.setText(_translate("InitDialog", "Cancel"))
        self.actionOpen_existing.setText(_translate("InitDialog", "Open existing"))

#import gomop_resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InitDialog = QtWidgets.QDialog()
    ui = Ui_InitDialog()
    ui.setupUi(InitDialog)
    InitDialog.show()
    sys.exit(app.exec_())

